steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'NEXT_PUBLIC_SUPABASE_URL=$$NEXT_PUBLIC_SUPABASE_URL',
        '--build-arg',
        'NEXT_PUBLIC_SUPABASE_ANON_KEY=$$NEXT_PUBLIC_SUPABASE_ANON_KEY',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/kaaseb-images/kaaseb-world',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/kaaseb-images/kaaseb-world'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'kaaseb-world',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/kaaseb-images/kaaseb-world',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

options:
  logging: CLOUD_LOGGING_ONLY